### ISSUE TITLE
'Multiple use of same option' error adding or removing rules more than once.

### ISSUE THREAD

**Issue by sqwishy** [ldx/python-ebtables#2]
When creating and deleting rules, the first call works, but subsequent ones fail with an error about duplicated options. So far I've only noticed this with rules involving match extensions.

```
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ebtables 
>>> ebtables.filter(['-A', 'INPUT', '--protocol', '802_1Q', '--vlan-id', '10', '-j', 'ACCEPT'])
(0, '', '')
>>> ebtables.filter(['-D', 'INPUT', '--protocol', '802_1Q', '--vlan-id', '10', '-j', 'ACCEPT'])
(-1, '', 'Multiple use of same option not allowed')
```

Things seem to work when restarting the interpreter between calls. So in the example above, the last line works as expected and the rule is deleted if you open a new interpreter and run it.

This was on version 0.1.1.

**Comment by ldx** [comment]
For me:

```
>>> import ebtables
>>> ebtables.filter(['-A', 'INPUT', '--protocol', '802_1Q', '--vlan-id', '10', '-j', 'ACCEPT'])
(0, '', '')
>>> ebtables.filter(['-D', 'INPUT', '--protocol', '802_1Q', '--vlan-id', '10', '-j', 'ACCEPT'])
(0, '', '')
>>>
```

Can you tell me your python/ebtables/python-ebtables versions?

**Comment by sqwishy** [comment]
It was on python-ebtables 0.1.1. But I don't believe the issue exists on master.

**Comment by ldx** [comment]
@sqwishy can you use master for your project? I also plan to make a new release on pypi.

**Comment by sqwishy** [comment]
Yeah, sounds good.

**Comment by ldx** [comment]
New version is now available on PyPI.
